[build]
  # Netlify will serve files from the public directory
  publish = "public"
  
  # No build command needed for static site
  command = ""

# Redirect all API calls to your backend (when you deploy it separately)
# For now, these will point to localhost during development
[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/api/:splat"
  status = 200
  force = true
  
# SPA fallback - redirect all requests to index.html for client-side routing
# This ensures direct URL access works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/cover_images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

